### ISSUE TITLE
Can we make clickable horizontal chart and generate pie chart on click on one bar of graph in Predix?

### ISSUE THREAD

**Issue by AsheeshShekhawat** [PredixDev/px-simple-horizontal-bar-chart#7]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by Menkhaus-ge** [comment]
Hi AsheeshShekhawat, 
It is a little unclear what you are asking. However, the purpose of the the simple charts is to be viewed on a dashboard. These charts are not meant to be interactive.

**Comment by AsheeshShekhawat** [comment]
Is There any chart having column with drilldown is available in predix?

**Comment by benoitjchevalier** [comment]
no
