### ISSUE TITLE
simple-horizontal-bar-chart issue with displaying values 

### ISSUE THREAD

**Issue by ravikiransharvirala** [PredixDev/px-simple-horizontal-bar-chart#8]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
Expected:
![screen shot 2017-03-10 at 2 30 28 pm](https://cloud.githubusercontent.com/assets/16749662/23815716/2c5ab15e-059e-11e7-861f-3ff2edb58a07.png)

Actual:
![screen shot 2017-03-10 at 2 15 48 pm](https://cloud.githubusercontent.com/assets/16749662/23815655/e705b496-059d-11e7-8f46-3844bccfedd6.png)

    
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Browser: Tried in Chrome(56.0.2924.87) and Safari(9.1.3) - issue persists in both browsers
OS: Mac
component version number: "version": "0.6.8"

Note: when I minimize the browser window and maximize the window back the values appear fine. The issue occurs only when the page loads.

**Comment by randyaskin** [comment]
I'm not seeing this issue in our demo page or in a CodePen. It looks like you're several versions behind (it's now at v0.8.5) - could you try running `bower update` and see if the issue still persists in the latest version?

**Comment by ravikiransharvirala** [comment]
Thanks randyaskin.
I tried updating the bower components by running bower update  but I am having  issues dealing component dependencies -- 

`Unable to find a suitable version for px-theme, please choose one by typing one of the numbers below:
    1) px-theme#~1.1.2 which resolved to 1.1.4 and is required by px-popover#1.5.1, px-vis#0.5.13, px-vis-timeseries#0.3.6, px-vis-xy-chart#0.1.3
    2) px-theme#^1.1.2 which resolved to 1.1.4 and is required by predix-seed
    3) px-theme#^2.0.1 which resolved to 2.0.4 and is required by polymer-font-awesome#0.1.11, px-calendar-picker#0.5.18, px-card#0.6.10, px-card#0.5.14, px-chart#1.7.8, px-context-browser#1.6.11, px-data-table#1.14.22, px-datetime-common#0.6.17, px-datetime-field#0.5.13, px-datetime-range-panel#0.3.11, px-deck-selector#1.6.7, px-dropdown#2.0.8, px-overlay#0.3.10, px-percent-circle#0.1.12, px-polymer-font-awesome#0.1.11, px-polymer-font-awesome#1.1.5, px-rangepicker#1.2.15, px-sample-cards#0.6.6, px-simple-bar-chart#1.6.14, px-simple-horizontal-bar-chart#0.6.15, px-simple-line-chart#1.5.11, px-spinner#0.5.3, px-tooltip#0.9.19, px-tooltip#0.10.18, px-validation#0.3.8, px-view-header#0.1.10, px-widget-cards#2.1.11, px-widget-cards#2.3.1
    4) px-theme#^2.0.2 which resolved to 2.0.4 and is required by px-simple-bar-chart#1.9.1
    5) px-theme#^2.0.4 which resolved to 2.0.4 and is required by px-app-nav#1.10.9

Prefix the choice with ! to persist it to bower.json`

 I selected based on the components I am using and when I built it the component disappeared. Can you let me know how to deal with these dependencies during updating the components or installing them?

**Comment by randyaskin** [comment]
Generally when this happens, you just need to `rm -rf bower_components` and re-run `bower install`

**Comment by randyaskin** [comment]
Any luck?

**Comment by ravikiransharvirala** [comment]
Nope. Tried it again today.

**Comment by randyaskin** [comment]
On second thought, I picked a bad time to ask. :)  Martin just started issuing major revisions to our components as part of the design refresh underway, which is going to cause temporary resolution issues all over the place until we can get all of the foundational elements cut over. For the time being, you can just choose the latest version (the largest numeric choice) when running bower update.

**Comment by nonmetalhail** [comment]
I think the problem this is via the seed, yes? Have you updated the seed? Even with the latest seed, you'll probably run into this problem because it is behind

**Comment by ravikiransharvirala** [comment]
Ok. When can we expect the latest revisions?
Thank you

**Comment by nonmetalhail** [comment]
The major revisions Randy is talking about are occurring this quarter. I dont know of an ETA when they will be done. 

If you are using the seed, that is developed by another group so I can give no info on it or when it will be up to date with our components. You may want to open an issue on the seed if it's components are out of date.
